import AppKit
import ApplicationServices
import Carbon.HIToolbox
import Foundation
import os

/// Inserts dictated text into the frontmost app. Primary strategy is a verified
/// synthetic paste (fill clipboard → simulate Cmd+V → poll the focused AX state
/// to confirm the text landed). When paste can't be verified, the text is left
/// on the clipboard as a manual fallback. AX insertion is used only when the
/// clipboard should be preserved.
@MainActor
final class TextInsertionService {
    static let shared = TextInsertionService()

    private let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "piszeprogramy.openWhisper", category: "insertion")

    /// Terminal + Firefox apps handle synthetic paste best; AX value writes are
    /// unreliable there.
    private static let pastePreferredBundleIDs: Set<String> = [
        "com.apple.Terminal",
        "com.googlecode.iterm2",
        "com.github.wez.wezterm",
        "dev.warp.Warp",
        "dev.warp.Warp-Stable",
        "dev.warp.Warp-Preview",
        "dev.warp.WarpPreview",
        "com.mitchellh.ghostty",
        "org.mozilla.firefox",
        "org.mozilla.firefoxdeveloperedition",
        "org.mozilla.nightly",
    ]

    private static let textRoles: Set<String> = [
        kAXTextFieldRole, kAXTextAreaRole, kAXComboBoxRole, "AXSearchField", "AXWebArea"
    ]

    private static let transientMarkerTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.openwhisper.SpeechTranscription"),
    ]

    /// Roles where a synthetic paste reliably replaces the selection in place.
    /// Web areas and other read-only elements fall back to the clipboard.
    private static let pasteEditableRoles: Set<String> = [
        kAXTextFieldRole, kAXTextAreaRole, kAXComboBoxRole, "AXSearchField"
    ]

    /// What the reformat hotkey captured from the focused element.
    struct CapturedSelection {
        /// Text to process: the selection, or the whole field when editable with
        /// no selection.
        let text: String
        let hasSelection: Bool
        /// Whether the text lives in an editable input we can replace in place.
        let editable: Bool
        /// The focused element, present only when `editable`.
        let element: AXUIElement?
    }

    var isAccessibilityGranted: Bool { AXIsProcessTrusted() }

    func requestAccessibilityPermission() {
        let options = ["AXTrustedCheckOptionPrompt" as CFString: true] as CFDictionary
        AXIsProcessTrustedWithOptions(options)
        if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility") {
            NSWorkspace.shared.open(url)
        }
    }

    func captureActiveApp() -> (name: String?, bundleId: String?) {
        let app = NSWorkspace.shared.frontmostApplication
        return (app?.localizedName, app?.bundleIdentifier)
    }

    /// Inserts `text` into the frontmost app. Always fills the clipboard first
    /// so the user can paste manually if automated insertion fails.
    ///
    /// - Parameters:
    ///   - text: the text to insert.
    ///   - outputFormat: optional rich format (e.g. "rtf") that produces a
    ///     formatted pasteboard payload; nil = plain text.
    ///   - preserveClipboard: restore the previous clipboard after pasting.
    /// - Returns: whether the text was inserted (verified paste or verified AX).
    @discardableResult
    func insertText(_ text: String, outputFormat: String? = nil, preserveClipboard: Bool = false) async -> Bool {
        guard !text.isEmpty else { return false }
        guard isAccessibilityGranted else { return false }

        let activeApp = captureActiveApp()
        let prefersPaste = activeApp.bundleId.map { Self.pastePreferredBundleIDs.contains($0) } ?? false
        let richPayload = PasteboardContentFormatter.payload(for: text, format: outputFormat)

        if preserveClipboard, !prefersPaste, richPayload == nil, let element = focusedTextElement(),
           insertTextAt(element: element, text: text) {
            return true
        }

        let pasteboard = NSPasteboard.general
        let savedItems = preserveClipboard ? saveClipboard(from: pasteboard) : nil
        let initialState = focusedTextState()

        pasteboard.clearContents()
        if let richPayload {
            richPayload.write(to: pasteboard, markerTypes: Self.transientMarkerTypes)
        } else {
            writeTranscription(to: pasteboard, text: text)
        }

        simulatePaste()

        let verified = await waitForPasteVerification(baseline: initialState)
        if !verified {
            logger.info("Paste not verified; text left on clipboard")
        }

        if preserveClipboard, let savedItems {
            // Give the app time to read the pasteboard, then restore.
            try? await Task.sleep(for: .milliseconds(500))
            restoreClipboard(savedItems, to: pasteboard)
        }

        return verified
    }

    // MARK: - Pasteboard

    private func writeTranscription(to pasteboard: NSPasteboard, text: String) {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for marker in Self.transientMarkerTypes {
            item.setData(Data(), forType: marker)
        }
        pasteboard.writeObjects([item])
    }

    private func saveClipboard(from pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        pasteboard.pasteboardItems ?? []
    }

    private func restoreClipboard(_ items: [NSPasteboardItem], to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        if !items.isEmpty {
            pasteboard.writeObjects(items)
        }
    }

    // MARK: - AX

    /// Captures the text the reformat hotkey should process from the focused
    /// element. Returns the selection when present; for an editable field with
    /// no selection, the whole field value. Returns nil when there is nothing to
    /// process (no focused element, empty text, or a password field that AX does
    /// not expose).
    func captureActiveSelection() -> CapturedSelection? {
        guard let element = systemFocusedElement() else { return nil }

        var valueValue: AnyObject?
        AXUIElementCopyAttributeValue(element, kAXValueAttribute as CFString, &valueValue)
        var selectedValue: AnyObject?
        AXUIElementCopyAttributeValue(element, kAXSelectedTextAttribute as CFString, &selectedValue)
        var rangeValue: AnyObject?
        AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &rangeValue)

        let value = (valueValue as? String) ?? ""
        let selectedText = (selectedValue as? String) ?? ""
        let range = nsRange(from: rangeValue)
        let hasSelection = (range?.length ?? 0) > 0
        let editable = isEditableInput(element)

        let text: String
        if editable, !hasSelection, !value.isEmpty {
            text = value
        } else {
            text = selectedText
        }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        return CapturedSelection(
            text: trimmed,
            hasSelection: hasSelection,
            editable: editable,
            element: editable ? element : nil
        )
    }

    /// Replaces the captured text in place with `text`. For a selection the
    /// existing paste path replaces it; for a whole-field capture the field is
    /// selected all first. Returns whether the paste was verified.
    @discardableResult
    func replaceFocusedText(
        _ text: String,
        selection: CapturedSelection,
        outputFormat: String? = nil,
        preserveClipboard: Bool = false
    ) async -> Bool {
        guard selection.editable, let element = selection.element else { return false }
        if !selection.hasSelection {
            _ = selectAll(element)
        }
        return await insertText(text, outputFormat: outputFormat, preserveClipboard: preserveClipboard)
    }

    private func systemFocusedElement() -> AXUIElement? {
        let systemWide = AXUIElementCreateSystemWide()
        var focused: AnyObject?
        guard AXUIElementCopyAttributeValue(systemWide, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
              let focused else { return nil }
        return focused as! AXUIElement
    }

    /// Whether `element` is an editable text input we can replace with a paste.
    private func isEditableInput(_ element: AXUIElement) -> Bool {
        var roleValue: AnyObject?
        AXUIElementCopyAttributeValue(element, kAXRoleAttribute as CFString, &roleValue)
        if let role = roleValue as? String, Self.pasteEditableRoles.contains(role) { return true }
        var editableValue: AnyObject?
        AXUIElementCopyAttributeValue(element, kAXIsEditableAttribute as CFString, &editableValue)
        return (editableValue as? Bool) == true
    }

    /// Selects the entire value of `element` via AX so a subsequent paste
    /// replaces the whole field. Returns whether the write was accepted.
    private func selectAll(_ element: AXUIElement) -> Bool {
        var valueValue: AnyObject?
        AXUIElementCopyAttributeValue(element, kAXValueAttribute as CFString, &valueValue)
        guard let value = valueValue as? String else { return false }
        let length = (value as NSString).length
        var range = CFRange(location: 0, length: length)
        guard let axRange = AXValueCreate(.cfRange, &range) else { return false }
        return AXUIElementSetAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, axRange) == .success
    }

    private func focusedTextElement() -> AXUIElement? {
        let systemWide = AXUIElementCreateSystemWide()
        var focused: AnyObject?
        guard AXUIElementCopyAttributeValue(systemWide, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
              let focused else { return nil }

        let element = focused as! AXUIElement
        var roleValue: AnyObject?
        guard AXUIElementCopyAttributeValue(element, kAXRoleAttribute as CFString, &roleValue) == .success,
              let role = roleValue as? String,
              Self.textRoles.contains(role) else { return nil }
        return element
    }

    private func insertTextAt(element: AXUIElement, text: String) -> Bool {
        let result = AXUIElementSetAttributeValue(
            element, kAXSelectedTextAttribute as CFString, text as CFTypeRef
        )
        return result == .success
    }

    private struct FocusedTextState {
        let value: String?
        let selectedText: String?
        let selectedRange: NSRange?
    }

    private func focusedTextState() -> FocusedTextState? {
        guard let element = focusedTextElement() else { return nil }
        var valueValue: AnyObject?
        AXUIElementCopyAttributeValue(element, kAXValueAttribute as CFString, &valueValue)
        var selectionValue: AnyObject?
        AXUIElementCopyAttributeValue(element, kAXSelectedTextAttribute as CFString, &selectionValue)
        var rangeValue: AnyObject?
        AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &rangeValue)
        return FocusedTextState(
            value: valueValue as? String,
            selectedText: selectionValue as? String,
            selectedRange: nsRange(from: rangeValue)
        )
    }

    private func nsRange(from value: AnyObject?) -> NSRange? {
        guard let value, CFGetTypeID(value) == AXValueGetTypeID() else { return nil }
        var range = CFRange()
        guard AXValueGetValue(value as! AXValue, .cfRange, &range) else { return nil }
        return NSRange(location: range.location, length: range.length)
    }

    private func stateDidChange(from baseline: FocusedTextState?) -> Bool {
        guard let baseline, let current = focusedTextState() else { return false }
        return baseline.value != current.value
            || baseline.selectedText != current.selectedText
            || baseline.selectedRange != current.selectedRange
    }

    private func waitForPasteVerification(baseline: FocusedTextState?, attempts: Int = 10, delay: Duration = .milliseconds(50)) async -> Bool {
        guard baseline != nil else { return false }
        for _ in 0..<attempts {
            if stateDidChange(from: baseline) { return true }
            try? await Task.sleep(for: delay)
        }
        return stateDidChange(from: baseline)
    }

    // MARK: - Synthetic events

    private func simulatePaste() {
        let vKey = virtualKeyCode(for: "v") ?? 0x09
        postKey(keyCode: vKey, flags: .maskCommand)
    }

    private func postKey(keyCode: CGKeyCode, flags: CGEventFlags) {
        let down = CGEvent(keyboardEventSource: nil, virtualKey: keyCode, keyDown: true)
        down?.flags = flags
        down?.post(tap: .cgSessionEventTap)
        let up = CGEvent(keyboardEventSource: nil, virtualKey: keyCode, keyDown: false)
        up?.flags = flags
        up?.post(tap: .cgSessionEventTap)
    }

    /// Resolves the physical key code for a character in the current layout.
    private func virtualKeyCode(for character: String) -> CGKeyCode? {
        guard let source = TISCopyCurrentKeyboardInputSource()?.takeRetainedValue(),
              let layoutDataRef = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            return nil
        }
        let layoutData = unsafeBitCast(layoutDataRef, to: CFData.self)
        let keyLayout = unsafeBitCast(CFDataGetBytePtr(layoutData), to: UnsafePointer<UCKeyboardLayout>.self)

        var deadKeyState: UInt32 = 0
        var chars = [UniChar](repeating: 0, count: 4)
        var length = 0

        for keyCode: UInt16 in 0...127 {
            deadKeyState = 0
            let status = UCKeyTranslate(
                keyLayout, keyCode, UInt16(kUCKeyActionDown), 0,
                UInt32(LMGetKbdType()), UInt32(kUCKeyTranslateNoDeadKeysMask),
                &deadKeyState, chars.count, &length, &chars
            )
            if status == noErr, length > 0,
               String(utf16CodeUnits: chars, count: length) == character {
                return CGKeyCode(keyCode)
            }
        }
        return nil
    }
}
